ARG UBI_BASE_IMAGE=ubi7
FROM registry.access.redhat.com/${UBI_BASE_IMAGE}

LABEL name="postfix"
LABEL version="latest"

RUN yum -y update \
    && rpm -i https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && yum install -y \
        ca-certificates \
        postfix \
        rsyslog \
        supervisor \
    && yum clean all

COPY ./supervisor.conf /etc/supervisord.d/postfix.ini

COPY ./bin/postfix_init.sh /postfix_init.sh
RUN chmod u+x /postfix_init.sh

CMD ["/usr/bin/python", "/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
